os: osx
language: swift
osx_image: xcode11.6
script: xcodebuild clean build test -project TheMovieDB.xcodeproj -scheme TheMovieDB -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=13.6,name=iPhone 11' ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO